export const CardsData = [
    {id:1,
    imageUrl:require("./assets/img/Navito.png"),
    title:"Navito Fungicide",
    discount:"11%",
    subtext:"Bayer",
    rating:4.1,
    offer:"1 kg(offers applicable)",
    discountPrice:'9,229',
    originalPrice:'10,300'
    },
    {
        id:2,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:3,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:4,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:5,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:6,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:7,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:8,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:9,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:10,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:11,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:12,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:13,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:14,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:15,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:16,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:17,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:18,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:19,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },
    {
        id:20,
        imageUrl:require("./assets/img/Alika.png"),
        title:"Alika Insecticide",
        discount:"34%",
        subtext:"Syngeta",
        rating:4.1,
        offer:"40 ml(offers applicable)",
        discountPrice:'151',
        originalPrice:'299'
    },  {
        id: 21,
        imageUrl: require("./assets/img/Alika.png"),
        title: "Alika Insecticide",
        discount: "34%",
        subtext: "Syngeta",
        rating: 4.1,
        offer: "40 ml(offers applicable)",
        discountPrice: '151',
        originalPrice: '299'
      },
      {
        id: 22,
        imageUrl: require("./assets/img/Alika.png"),
        title: "Alika Insecticide",
        discount: "34%",
        subtext: "Syngeta",
        rating: 4.1,
        offer: "40 ml(offers applicable)",
        discountPrice: '151',
        originalPrice: '299'
      },
      {
        id: 23,
        imageUrl: require("./assets/img/Alika.png"),
        title: "Alika Insecticide",
        discount: "34%",
        subtext: "Syngeta",
        rating: 4.1,
        offer: "40 ml(offers applicable)",
        discountPrice: '151',
        originalPrice: '299'
      },
      {
        id: 24,
        imageUrl: require("./assets/img/Alika.png"),
        title: "Alika Insecticide",
        discount: "34%",
        subtext: "Syngeta",
        rating: 4.1,
        offer: "40 ml(offers applicable)",
        discountPrice: '151',
        originalPrice: '299'
      }

]